### ISSUE TITLE
Pod5, SLOW5/BLOW5 files

### ISSUE THREAD

**Issue by Stakaitis** [MaestSi/nf-m6anet#2]
Does this pipeline also work with .pod5 or .blow5 files as input?

Thank You!

**Comment by MaestSi** [comment]
Hi, I think f5c does not support pod5 yet. You should first convert pod5 to fast5, and then run the pipeline.
Best,
SM

**Comment by Stakaitis** [comment]
Thank You for a quick reply!
f5c seems to work with .slow5 files (https://github.com/hasindu2008/f5c#usage), so this means that nf-m6anet pipeline should also work with .slow5 files, right?

**Comment by MaestSi** [comment]
Possibly, but I never tested it with slow5.
SM

**Comment by Stakaitis** [comment]
Ok. 
I'll test it out and open this comment if I run into any issues.
Thanks!
